<?php

declare(strict_types=1);

return [
    'title' => 'Laravel Pizza Meetups',
    'sitename' => 'Laravel Pizza Meetups',
    'subtitle' => 'Join fellow Laravel, Filament, and Livewire enthusiasts for pizza meetups!!',
    'sottotitolo_comune' => '',
    'generator' => '',
    'charset' => 'UTF-8',
    'author' => '',
    'description' => '',
    'keywords' => '',
    'nome_regione' => '',
    'nome_comune' => '',
    'site_title' => '',
    'favicon' => 'pub_theme::img/favicon.ico',
    'logo_img' => 'pub_theme::img/logo.svg',
    'logo_square' => 'pub_theme::img/logo.svg',
    'logo_footer_img' => 'pub_theme::img/logo.svg',
    'logo_alt' => 'Logo',
    'logo_header_dark' => 'pub_theme::img/logo.svg',
    'logo_header' => 'pub_theme::img/logo.svg',
    'hide_megamenu' => false,
    'hero_type' => 'with_megamenu_bottom',
    'facebook_href' => 'aa',
    'twitter_href' => '',
    'youtube_href' => '',
    'fastlink' => false,
    'color_primary' => '#0071b0',
    'color_title' => 'white',
    'color_megamenu' => '#d60021',
    'color_hamburger' => '#000',
    'color_banner' => '#000',
];
