<?php

declare(strict_types=1);

return [
    'locale' => 'it',
    'timezone' => 'Europe/Berlin',
    'date_format' => 'd/m/Y',
    'datetime_format' => 'd/m/Y H:i:s',
    'currency' => 'EUR',
    'currency_symbol' => '€',
    'currency_decimal_separator' => ',',
    'currency_thousand_separator' => '.',
    'currency_decimal_places' => 2,
    'currency_display_format' => '€ #,##0.00',
    'currency_display_format_negative' => '-€ #,##0.00',
    'currency_display_format_positive' => '+€ #,##0.00',
    'currency_display_format_zero' => '€ 0,00',
    'currency_display_format_nan' => '€ N/A',
    'currency_display_format_infinity' => '€ ∞',
    'currency_display_format_short' => '€ #,##0',
    'currency_display_format_short_negative' => '-€ #,##0',
    'currency_display_format_short_positive' => '+€ #,##0',
    'currency_display_format_short_zero' => '€ 0',
    'currency_display_format_short_nan' => '€ N/A',
    'currency_display_format_short_infinity' => '€ ∞',
    'currency_display_format_long' => '€ #,##0.00',
    'currency_display_format_long_negative' => '-€ #,##0.00',
    'currency_display_format_long_positive' => '+€ #,##0.00',
    'currency_display_format_long_zero' => '€ 0,00',
    'currency_display_format_long_nan' => '€ N/A',
    'currency_display_format_long_infinity' => '€ ∞',
    'currency_display_format_currency_code' => '€ #,##0.00 [EUR]',
    'currency_display_format_currency_code_negative' => '-€ #,##0.00 [EUR]',
    'currency_display_format_currency_code_positive' => '+€ #,##0.00 [EUR]',
    'currency_display_format_currency_code_zero' => '€ 0,00 [EUR]',
    'currency_display_format_currency_code_nan' => '€ N/A [EUR]',
    'currency_display_format_currency_code_infinity' => '€ ∞ [EUR]',
    'currency_display_format_currency_code_short' => '€ #,##0 [EUR]',
    'currency_display_format_currency_code_short_negative' => '-€ #,##0 [EUR]',
    'currency_display_format_currency_code_short_positive' => '+€ #,##0 [EUR]',
    'currency_display_format_currency_code_short_zero' => '€ 0 [EUR]',
    'currency_display_format_currency_code_short_nan' => '€ N/A [EUR]',
    'currency_display_format_currency_code_short_infinity' => '€ ∞ [EUR]',
    'currency_display_format_short' => '€ #,##0.00',
    'currency_display_format_short_negative' => '-€ #,##0.00',
    'currency_display_format_short_positive' => '+€ #,##0.00',
    'currency_display_format_short_zero' => '€ 0,00',
    'currency_display_format_short_nan' => '€ N/A',
    'currency_display_format_short_infinity' => '€ ∞',
];
