name: Pest Test Coverage

on:
  push:
    branches:
      - main
      - master
      - dev
      - develop

jobs:
  laravel-tests:
    runs-on: ubuntu-latest

    strategy:
      matrix:
        operating-system: [ubuntu-latest]
        php-versions: ['8.3'] # Updated to match Laraxot PHP 8.3 requirement

    name: P${{ matrix.php-versions }} - ${{ matrix.operating-system}}

    steps:
      - uses: actions/checkout@v2

      - name: Install PHP versions with PCOV
        uses: shivammathur/setup-php@v2
        with:
          php-version: ${{ matrix.php-versions }}
          coverage: pcov # PCOV is highly recommended for fast coverage generation with Pest

      - name: Check Directories
        run: pwd && ls -la

      - name: Install Dependencies
        working-directory: ./laravel
        run: composer install -q --no-ansi --no-interaction --no-scripts --no-progress --prefer-dist

      - name: Execute tests and generate coverage via PestPHP
        working-directory: ./laravel
        env:
          SESSION_DRIVER: array
          DB_CONNECTION: testing # ensure testing connection is used
        run: ./vendor/bin/pest --coverage --coverage-clover ../clover.xml

      - name: Generate test coverage badge
        uses: timkrase/phpunit-coverage-badge@v1.2.0
        with:
          coverage_badge_path: 'badge-coverage.svg'
          push_badge: true
          repo_token: ${{ secrets.GITHUB_TOKEN }}
          report: clover.xml # The badge action will read the clover.xml generated in the root directory